# Generated by Django 4.1.1 on 2022-10-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_productdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagedeatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(max_length=255, upload_to='')),
            ],
        ),
    ]
