# Generated by Django 4.1.1 on 2022-10-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_imagedeatails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedeatails',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
